Repository iOS05-Stargazers/STAR, pull requests merged in 2025-02, with the labels that each got.

#86 온보딩 페이지 구현 #27
  star/star/Source/Jerry/Onboarding/OnboardingView.swift
  star/star/Source/Jerry/Onboarding/OnboardingViewController.swift
  star/star/Source/Mun/StarList/StarListView/StarListViewController.swift
Labels: enhancement

#88 PermissionView MVC에서 MVVM으로 리팩토링
  star/star.xcodeproj/project.pbxproj
  star/star/Source/Eden/PermissionViewController.swift
  star/star/Source/Eden/PermissionViewModel.swift
  star/star/star.entitlements
Labels: bug, enhancement

#91 앱 실행 시 권한 승인 상태여도 PermissionViewController가 먼저 표시되는 오류 수정
  star/star/App/SceneDelegate.swift
Labels: bug

#100 PermissionView 문구 수정
  star/star/Source/Eden/PermissionView.swift
  star/star/Source/Eden/PermissionViewController.swift
Labels: help wanted

#102 CoreDataManager를 UserDefaultsManager로 리팩토링 #94
  star/star/Source/Jerry/Star/JSONCodable.swift
  star/star/Source/Jerry/Star/MockData.swift
  star/star/Source/Jerry/Star/Schedule/Schedule.swift
  star/star/Source/Jerry/Star/Schedule/StarTime/StarTime.swift
  star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDay.swift
  star/star/Source/Jerry/Star/Star.swift
  star/star/Source/Jerry/Star/UserDefaultsManager/StarIDFormatter.swift
  star/star/Source/Jerry/Star/UserDefaultsManager/StarIDManager.swift
  star/star/Source/Jerry/Star/UserDefaultsManager/StarUserDefaultsManager.swift
  star/star/Source/Jerry/Star/UserDefaultsManager/StarUserDefaultsManagerTester.swift
Labels: enhancement

#105 스타 생성 모달 datePicker 구현 #87
  star/star/Source/Glass/StarModalView.swift
  star/star/Source/Glass/StarModalViewController.swift
  star/star/Source/Glass/StarModalViewModel.swift
Labels: enhancement

#109 WeekDayButton 구현 #108
  star/star/Source/Core/UIComponent/GradientButton.swift
  star/star/Source/Jerry/WeekDayButton.swift
Labels: enhancement

#116 휴식 화면 플로우에 사용되는 Color Assets 추가
  star/star/Resource/Colors.xcassets/starAlertModalOverlayBG.colorset/Contents.json
  star/star/Resource/Colors.xcassets/starButtonGray.colorset/Contents.json
  star/star/Resource/Colors.xcassets/starButtonWhite.colorset/Contents.json
  star/star/Resource/Colors.xcassets/starButtonYellow.colorset/Contents.json
  star/star/Resource/Colors.xcassets/starModalOverlayBG.colorset/Contents.json
Labels: enhancement

#112 스타 수정하기 구현 #110
  star/star/Source/Glass/StarModalView.swift
  star/star/Source/Glass/StarModalViewController.swift
  star/star/Source/Glass/StarModalViewModel.swift
  star/star/Source/Jerry/WeekDayButton.swift
  star/star/Source/Mun/StarList/StarListView/StarListViewController.swift
Labels: enhancement

#129 휴식 시간설정 모달 UI 구현
  star/star/Source/Glass/RestSettingModalViewController.swift
Labels: enhancement

#136 휴식 UserDefaults 구현 #133
  star/star/Source/Glass/RestSettingModalViewController.swift
  star/star/Source/Glass/RestTimeUserDefaults+Extension.swift
Labels: enhancement

#148 휴식하기 UserDefaults 삭제 구현
  star/star/Source/Glass/RestSettingModalViewController.swift
  star/star/Source/Glass/UserDefaults+RestTime.swift
Labels: enhancement

#149 휴식중 끝나면 UserDefaults에 저장되었던 휴식시간 삭제, 타이머 00:01에서 멈추는 버그 수정
  star/star/Source/Eden/RestingViewController.swift
  star/star/Source/Eden/RestingViewModel.swift
Labels: bug

#162 스타 생성하기/수정하기 모달 리팩토링 & 시간설정 DatePicker → UIPickerView 변경
  star/star/Source/Glass/CustomPresentationController.swift
  star/star/Source/Glass/CustomView/CustomGrabberView.swift
  star/star/Source/Glass/StarModalView.swift
  star/star/Source/Glass/StarModalViewController.swift
  star/star/Source/Glass/StarModalViewModel.swift
  star/star/Source/Glass/TimePickerModal/PickerViewAdapter.swift
  star/star/Source/Glass/TimePickerModal/TimePickerModalView.swift
  star/star/Source/Glass/TimePickerModal/TimePickerModalViewController.swift
  star/star/Source/Glass/TimePickerModal/TimePickerModalViewModel.swift
  star/star/Source/Jerry/WeekDayButton.swift
  star/star/Source/Mun/StarList/StarListView/CustomModalTransition.swift
  star/star/Source/Mun/StarList/StarListView/StarListViewController.swift
Labels: enhancement

#164 휴식기능 ScreenTime 기능 연결 #156
  star/DeviceActivityMonitor+Extension/DeviceActivityMonitorExtension.swift
  star/star.xcodeproj/project.pbxproj
  star/star/Source/Core/Extension/BlockManager.swift
  star/star/Source/Core/Extension/DeviceActivityName+Extension.swift
  star/star/Source/Core/Extension/FamilyAcitivitySelection+Extension.swift
  star/star/Source/Core/Utility/PreviewProvider.swift
  star/star/Source/Eden/FamilyControlsManager.swift
  star/star/Source/Eden/RestingViewModel.swift
  star/star/Source/Glass/RestSettingModalViewController.swift
  star/star/Source/Glass/StarModalViewModel.swift
  star/star/Source/Glass/UserDefaults+RestTime.swift
  star/star/Source/Mun/StarDeleteAlert/StarDeleteAlertViewModel.swift
  star/star/Source/Mun/StarList/StarListViewModel/StarListViewModel.swift
Labels: enhancement

#174 스타 모달 높이 디바이스별 대응
  star/star/Source/Glass/CustomPresentationController.swift
Labels: enhancement

#176 온보딩 뷰 버그 삭제
  star/star/Source/Eden/Onboarding/OnboardingCollectionView.swift
  star/star/Source/Eden/Onboarding/OnboardingModel.swift
  star/star/Source/Eden/Onboarding/OnboardingViewModel.swift
Labels: bug

#195 starEdit 불필요 코드 삭제 # 181
  star/star/Source/Presentation/Rest/RestSettingModal/RestSettingModalViewController.swift
  star/star/Source/Presentation/StarEdit/StarEditViewController.swift
Labels: enhancement
