Repository iOS05-Stargazers/STAR, pull requests merged in 2025-04, with the labels that each got.

#249 앱 선택 라벨 표시 구현
  star/star/Resource/Localizable.xcstrings
  star/star/Source/Presentation/StarEdit/StarEditViewController.swift
  star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
Labels: enhancement

#245 시작시간이 종료시간을 초과하는 경우 스케쥴 설정
  star/star.xcodeproj/project.pbxproj
  star/star/Resource/Localizable.xcstrings
  star/star/Source/Core/Extension/DeviceActivityName+Extension.swift
  star/star/Source/Core/Extension/UserDefaults+Extension.swift
  star/star/Source/Core/Manager/BlockManager.swift
  star/star/Source/Core/Manager/FamilyControlsManager.swift
  star/star/Source/Core/Manager/NotificationManager.swift
  star/star/Source/Core/Manager/RestManager.swift
  star/star/Source/Core/Manager/StarManager/ScheduleCalculator.swift
  star/star/Source/Model/Star/Schedule/Schedule.swift
  star/star/Source/Model/Star/Schedule/ScheduleCalculator.swift
  star/star/Source/Model/Star/Schedule/StarTime/StarTime.swift
  star/star/Source/Model/Star/Schedule/WeekDay/WeekDay.swift
  star/star/Source/Model/StarState/StarState.swift
  star/star/Source/Presentation/Rest/RestSettingModal/RestSettingModalViewController.swift
  star/star/Source/Presentation/Rest/Resting/RestingViewModel.swift
  star/star/Source/Presentation/StarEdit/StarEditView.swift
  star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
  star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift
Labels: Refactor

#244 TimePicker에 무한 스크롤 효과 적용을 위한 로직 수정
  star/star/Source/Presentation/StarEdit/TimePickerModal/TimePickerModalViewController.swift
  star/star/Source/Presentation/StarEdit/TimePickerModal/TimePickerModalViewModel.swift
Labels: Refactor

#247 런치스크린, 배경화면 리뉴얼
  star/star/Resource/Assets.xcassets/cloudImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/cloudImage.imageset/cloud_ver6.png
  star/star/Source/Presentation/AppLaunch/AppLaunchViewController.swift
  star/star/Source/Presentation/AppLaunch/MeteorEffectView.swift
  star/star/Source/Presentation/AppLaunch/StarrayNightView.swift
  star/star/Source/Presentation/StarList/StarListView/StarListView.swift
  star/star/Source/Presentation/StarList/StarListView/StarListViewController.swift
Labels: Refactor

#259 시작시간과 종료시간이 같은 경우, 스타 생성 방지 (into develop)
  star/star/Source/Core/Theme/UIFont.swift
  star/star/Source/Presentation/Delay/DelayView.swift
  star/star/Source/Presentation/Rest/RestSettingModal/RestSettingModalViewController.swift
  star/star/Source/Presentation/Rest/Resting/RestingViewController.swift
  star/star/Source/Presentation/StarDeleteAlert/StarDeleteAlertViewController.swift
  star/star/Source/Presentation/StarEdit/StarEditView.swift
  star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
  star/star/Source/Presentation/StarEdit/TimePickerModal/TimePickerModalView.swift
  star/star/Source/Presentation/StarList/StarListView/StarListView.swift
Labels: bug

#258 시작시간과 종료시간이 같은 경우, 스타 생성 방지 (into main)
  star/star/Source/Core/Theme/UIFont.swift
  star/star/Source/Presentation/Delay/DelayView.swift
  star/star/Source/Presentation/Rest/RestSettingModal/RestSettingModalViewController.swift
  star/star/Source/Presentation/Rest/Resting/RestingViewController.swift
  star/star/Source/Presentation/StarDeleteAlert/StarDeleteAlertViewController.swift
  star/star/Source/Presentation/StarEdit/StarEditView.swift
  star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
  star/star/Source/Presentation/StarEdit/TimePickerModal/TimePickerModalView.swift
  star/star/Source/Presentation/StarList/StarListView/StarListView.swift
Labels: bug

#265 휴식 터치 화면 영역 수정
  star/star/Resource/Localizable.xcstrings
  star/star/Source/Core/Theme/UIFont.swift
  star/star/Source/Presentation/StarList/StarListView/StarListView.swift
  star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift
Labels: enhancement

#267 [Feat] 일본어 지원 추가
  star/star.xcodeproj/project.pbxproj
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/Group_2366.png
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/Group_2368.png
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/Group_2367.png
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/Frame_2281.png
  star/star/Resource/Localizable.xcstrings
  star/star/Source/Presentation/StarList/StarListView/StarListCollectionViewCell.swift
Labels: enhancement

#269 온보딩 화면 수정
  star/star.xcodeproj/project.pbxproj
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/Group 2361.png
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/Group 2369.png
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/Group 2372.png
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/Group_2366.png
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/onboardCreate.png
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/onboardingCreateImage.png
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/Group 2358.png
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/Group 2371.png
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/Group 2374.png
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/Group_2368.png
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/onboardDelete.png
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/onboardingDeleteImage.png
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/Group 2364.png
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/Group 2370.png
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/Group 2373.png
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/Group_2367.png
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/onboardModify.png
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/onboaringModifyImage.png
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/Frame 2280.png
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/Frame 2282.png
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/Frame 2283.png
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/Frame_2281.png
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/onboardRest.png
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/onboardingRestImage.png
  star/star/Source/Presentation/StarEdit/StarEditViewController.swift
Labels: enhancement

#272 스타 생성하기 권한 허용 예외 처리
  star/star/Resource/Localizable.xcstrings
  star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift
Labels: enhancement
