Repository iOS05-Stargazers/STAR, pull requests merged in 2025-01, with the labels that each got.

#1 [Add] Feature/project initialization - 프로젝트 초기화
  pull_request_template.md
  star/star.xcodeproj/project.pbxproj
  star/star.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  star/star/App/AppDelegate.swift
  star/star/App/Base.lproj/LaunchScreen.storyboard
  star/star/App/Info.plist
  star/star/App/SceneDelegate.swift
  star/star/App/star.xcdatamodeld/.xccurrentversion
  star/star/App/star.xcdatamodeld/star.xcdatamodel/contents
  star/star/App/starRelease.entitlements
  star/star/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  star/star/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  star/star/Resource/Assets.xcassets/Contents.json
  star/star/Source/DefaultViewController.swift
  star/star/Source/Eden/EdenPlaceholder.swift
  star/star/Source/Glass/GlassPlaceholder.swift
  star/star/Source/Jerry/JerryPlaceholder.swift
  star/star/Source/Maccha/MacchaPlaceholder.swift
  star/star/Source/Mun/MunPlaceholder.swift
  star/starTests/starTests.swift
  star/starUITests/starUITests.swift
  star/starUITests/starUITestsLaunchTests.swift
Labels: documentation

#36 버튼 컴포넌트 클래스 생성 #5 / 그라디언트 구현 메서드 제공 #31
  star/star/Source/Core/UIComponent/GradientButton.swift
  star/star/Source/DefaultViewController.swift
Labels: enhancement

#37 [Feat] 스타 모달 UI 구현
  star/star/Source/Glass/GlassPlaceholder.swift
  star/star/Source/Glass/StarModalView.swift
  star/star/Source/Glass/StarModalViewController.swift
Labels: enhancement

#46 스타 생성/수정 모달 텍스트필드 입력처리 #19
  star/star/Source/Glass/StarModalView.swift
  star/star/Source/Glass/StarModalViewController.swift
Labels: enhancement

#63 CoachMark 상태 관리하는 UserDefaultsManager 구현
  star/star.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  star/star/Source/Eden/UserDefaults+Extension.swift
Labels: enhancement, good first issue

#67 텍스트필드 삭제 버튼 구현 #50
  star/star/Source/Glass/StarModalView.swift
Labels: enhancement

#68 StarTime 생성자 재귀 오류 수정 #66
  star/star/Source/Jerry/Star/MockData.swift
  star/star/Source/Jerry/Star/Schedule/Schedule.swift
  star/star/Source/Jerry/Star/Schedule/StarTime/StarTime.swift
  star/star/Source/Jerry/Star/Schedule/StarTime/StarTimeFormatter.swift
  star/star/Source/Jerry/Star/Schedule/StarTime/StarTimeTranslator.swift
  star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDay.swift
  star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDayFormatter.swift
  star/star/Source/Jerry/Star/Schedule/WeekDay/WeekDayTranslator.swift
  star/star/Source/Jerry/Star/Star.swift
  star/star/Source/Jerry/Star/TestDescriptionConvertible.swift
  star/star/Source/Jerry/StarState/StarState.Style.swift
  star/star/Source/Jerry/StarState/StarState.swift
Labels: bug

#75 StarState 버그 수정 #74
  star/star/Source/Jerry/Star/MockData.swift
  star/star/Source/Jerry/Star/Schedule/Schedule.swift
  star/star/Source/Jerry/Star/Star.swift
  star/star/Source/Jerry/StarState/ScheduleCalculator.swift
  star/star/Source/Jerry/StarState/StarState.swift
Labels: bug

#76 PermissionViewController와 PermissionView 구현 후 FamilyControlsManager에 스크린타임 권한 설정 기능 구현
  star/star.xcodeproj/project.pbxproj
  star/star/App/SceneDelegate.swift
  star/star/Source/Eden/Extension/UILabel+Star.swift
  star/star/Source/Eden/Extension/UIStackView+Extension.swift
  star/star/Source/Eden/Extension/UIView+Extension.swift
  star/star/Source/Eden/Extension/UserDefaults+Extension.swift
  star/star/Source/Eden/FamilyControlsManager.swift
  star/star/Source/Eden/PermissionView.swift
  star/star/Source/Eden/PermissionViewController.swift
  star/star/Source/Mun/StarListViewController.swift
  star/star/star.entitlements
Labels: enhancement, good first issue

#77 스타 생성하기/수정하기 모달 MVVM 리팩토링 #70
  star/star/Source/Glass/StarModalView.swift
  star/star/Source/Glass/StarModalViewController.swift
  star/star/Source/Glass/StarModalViewModel.swift
Labels: enhancement

#85 [Feat] 스타 생성하기 (목 데이터) 구현
  star/star/Source/Glass/StarModalView.swift
  star/star/Source/Glass/StarModalViewController.swift
  star/star/Source/Glass/StarModalViewModel.swift
Labels: enhancement
