Repository iOS05-Stargazers/STAR, pull requests merged in 2025-03, with the labels that each got.

#204 Localization 구현
  star/ShieldConfiguration+Extension/ShieldConfigurationExtension.swift
  star/star.xcodeproj/project.pbxproj
  star/star/App/Info.plist
  star/star/App/ko.lproj/LaunchScreen.strings
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingCreateImage.imageset/onboardCreate.png
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingDeleteImage.imageset/onboardDelete.png
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingModifyImage.imageset/onboardModify.png
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/Contents.json
  star/star/Resource/Assets.xcassets/onboardingRestImage.imageset/onboardRest.png
  star/star/Resource/en.lproj/Localizable.strings
  star/star/Resource/ko.lproj/Localizable.strings
  star/star/Source/Core/Extension/String+Localization.swift
  star/star/Source/Core/Extension/UILabel+Extension.swift
  star/star/Source/Core/Manager/NotificationManager.swift
  star/star/Source/Model/Star/Schedule/WeekDay/WeekDay.swift
  star/star/Source/Model/Star/Schedule/WeekDay/WeekDayFormatter.swift
  star/star/Source/Model/Star/Schedule/WeekDay/WeekDayTranslator.swift
  star/star/Source/Model/StarListModel/TodayDate.swift
  star/star/Source/Model/StarState/StarStateFormatter.swift
  star/star/Source/Presentation/AppLaunch/AppLaunchViewController.swift
  star/star/Source/Presentation/CustomView/UIComponent/WeekDayButton.swift
  star/star/Source/Presentation/Delay/DelayView.swift
  star/star/Source/Presentation/Onboarding/OnboardingCell.swift
  star/star/Source/Presentation/Onboarding/OnboardingCollectionView.swift
  star/star/Source/Presentation/Onboarding/OnboardingViewModel.swift
  star/star/Source/Presentation/Permission/PermissionView.swift
  star/star/Source/Presentation/Rest/RestSettingModal/RestSettingModalViewController.swift
  star/star/Source/Presentation/Rest/Resting/RestingViewController.swift
  star/star/Source/Presentation/StarDeleteAlert/StarDeleteAlertViewController.swift
  star/star/Source/Presentation/StarEdit/StarEditView.swift
  star/star/Source/Presentation/StarEdit/StarEditViewController.swift
  star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
  star/star/Source/Presentation/StarEdit/TimePickerModal/TimePickerModalView.swift
  star/star/Source/Presentation/StarList/StarListView/StarListCollectionViewCell.swift
  star/star/Source/Presentation/StarList/StarListView/StarListView.swift
  star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift
Labels: enhancement

#215 앱 오류에 대한 알럿 기능 구현
  star/star/Resource/en.lproj/Localizable.strings
  star/star/Resource/ko.lproj/Localizable.strings
  star/star/Source/Presentation/StarEdit/StarEditViewController.swift
Labels: enhancement

#218 스타 시작 안내 문구 추가
  star/star.xcodeproj/project.pbxproj
  star/star/Resource/en.lproj/Localizable.strings
  star/star/Resource/ko.lproj/Localizable.strings
  star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift
Labels: enhancement

#222 Merge release-1.0.2 into develop (bug fixes)
  star/star/Resource/en.lproj/Localizable.strings
  star/star/Resource/ko.lproj/Localizable.strings
  star/star/Source/Core/Extension/UserDefaults+Extension.swift
  star/star/Source/Core/Manager/NotificationManager.swift
  star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
  star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift
Labels: enhancement

#228 [develop] 1.1.0 버전 (FamilyControls 권한 설정 및 휴식기능 오류 수정)
  star/DeviceActivityMonitor/DeviceActivityMonitor.entitlements
  star/DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  star/DeviceActivityMonitor/DeviceActivityMonitorRelease.entitlements
  star/ShieldConfiguration/Info.plist
  star/ShieldConfiguration/Media.xcassets/Contents.json
  star/ShieldConfiguration/Media.xcassets/logoImage.imageset/Contents.json
  star/ShieldConfiguration/Media.xcassets/logoImage.imageset/appLogo.png
  star/ShieldConfiguration/ShieldConfiguration.entitlements
  star/ShieldConfiguration/ShieldConfigurationExtension.swift
  star/ShieldConfiguration/ShieldConfigurationRelease.entitlements
  star/star.xcodeproj/project.pbxproj
  star/star/Resource/en.lproj/Localizable.strings
  star/star/Resource/ko.lproj/Localizable.strings
  star/star/Source/Core/Manager/BlockManager.swift
  star/star/Source/Core/Manager/FamilyControlsManager.swift
  star/star/Source/Presentation/Onboarding/OnboardingViewModel.swift
  star/star/Source/Presentation/Rest/RestSettingModal/RestSettingModalViewController.swift
  star/star/Source/Presentation/StarEdit/StarEditView.swift
  star/star/Source/Presentation/StarEdit/StarEditViewController.swift
  star/star/Source/Presentation/StarEdit/StarEditViewModel.swift
  star/star/Source/Presentation/StarList/StarListView/StarListView.swift
  star/star/Source/Presentation/StarList/StarListView/StarListViewController.swift
  star/star/Source/Presentation/StarRefresgAlert/StarRefresgAlertViewController.swift
Labels: bug, enhancement

#236 스타 태그가 제대로 적용되지 않는 에러 해결
  star/star.xcodeproj/project.pbxproj
  star/star/Source/Presentation/StarList/StarListView/StarListCollectionViewCell.swift
  star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift
Labels: bug

#237 Hotfix: 스타 태그가 제대로 적용되지 않는 에러 해결
  star/star.xcodeproj/project.pbxproj
  star/star/Source/Presentation/StarList/StarListView/StarListCollectionViewCell.swift
  star/star/Source/Presentation/StarList/StarListViewModel/StarListViewModel.swift
Labels: bug
